---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/yaml-lint.yml .
  ansible-lint
  flake8
platforms:
  - name: instance-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    exposed_ports:
      - 8983/tcp
    published_ports:
      - 0.0.0.0:8983:8983/tcp
    privileged: true
    pre_build_image: true
    groups:
      - solr
  - name: instance-2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    exposed_ports:
      - 8983/tcp
    published_ports:
      - 0.0.0.0:8984:8983/tcp
    privileged: true
    pre_build_image: true
    groups:
      - solr
  - name: instance-3
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    exposed_ports:
      - 8983/tcp
    published_ports:
      - 0.0.0.0:8985:8983/tcp
    privileged: true
    pre_build_image: true
    groups:
      - solr
provisioner:
  name: ansible
  log: false
  options:
    vvv: false
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    host_vars:
      instance-1:
        solr_master: true
        zookeeper_id: 0
      instance-2:
        solr_master: false
        zookeeper_id: 1
      instance-3:
        solr_master: false
        zookeeper_id: 2
scenario:
  name: cluster
verifier:
  name: ansible
