---
- name: Prepare
  hosts: all
  become: true

  roles:
    - role: kevincoakley.facter

  post_tasks:
    - gem:
        name: facter
        state: present
        user_install: false
      when:
        - ansible_os_family == 'Debian'
